import 'dart:math';

import 'package:flutter/material.dart';

/// The visual identity of one world: its sky gradient and the ambient
/// particles that drift through it. The horizon silhouette comes from
/// `assets/images/worlds/<unitId>.png` (generated by content/gen-world-art.py;
/// missing files degrade gracefully to gradient + particles).
class WorldTheme {
  const WorldTheme(this.sky, this.particles);

  /// Top→bottom sky gradient. Deliberately light — every world must keep
  /// dark text and solid UI chips readable on top of it.
  final List<Color> sky;

  /// Emoji that drift through this world's air.
  final List<String> particles;
}

const Map<int, WorldTheme> kWorldThemes = {
  1: WorldTheme([Color(0xFFCDEBFF), Color(0xFFF3FBEA)], ['🦋', '🍃']), // meadow
  2: WorldTheme([Color(0xFFFFF4D6), Color(0xFFFDEBC8)], ['🌾', '🐝']), // farm
  3: WorldTheme([Color(0xFFE8EAF6), Color(0xFFF6F2FA)], ['☁️', '🐦']), // town
  4: WorldTheme([Color(0xFFC5CAE9), Color(0xFFE8EAF6)], ['✨', '🌙']), // dusk
  5: WorldTheme([Color(0xFFFDEEF4), Color(0xFFEAF7E6)], ['🌸', '🌼']), // garden
  6: WorldTheme([Color(0xFFD6EFFF), Color(0xFFFFFFFF)], ['☁️', '❄️']), // sky
  7: WorldTheme([Color(0xFFF3E5F5), Color(0xFFE1F5FE)], ['✨', '⭐']), // magic
};

WorldTheme worldThemeFor(int unitId) => kWorldThemes[unitId] ?? kWorldThemes[1]!;

/// The immersive backdrop behind the home screen: sky gradient, generated
/// horizon art, and a slow drift of ambient emoji particles. Cross-fades when
/// the world changes.
class WorldScenery extends StatefulWidget {
  const WorldScenery({super.key, required this.unitId});

  final int unitId;

  /// Test seam: widget tests set this false so screens can settle
  /// (the drift loop otherwise never ends).
  static bool animate = true;

  @override
  State<WorldScenery> createState() => _WorldSceneryState();
}

class _WorldSceneryState extends State<WorldScenery>
    with SingleTickerProviderStateMixin {
  late final AnimationController _drift = AnimationController(
    vsync: this,
    duration: const Duration(seconds: 36),
  );

  @override
  void initState() {
    super.initState();
    if (WorldScenery.animate) {
      _drift.repeat();
    } else {
      _drift.value = 0.35; // a pleasant static frame
    }
  }

  @override
  void dispose() {
    _drift.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = worldThemeFor(widget.unitId);
    return AnimatedSwitcher(
      duration: const Duration(milliseconds: 600),
      child: Stack(
        key: ValueKey(widget.unitId),
        fit: StackFit.expand,
        children: [
          DecoratedBox(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: theme.sky,
              ),
            ),
          ),
          Align(
            alignment: Alignment.bottomCenter,
            child: Image.asset(
              'assets/images/worlds/${widget.unitId}.png',
              width: double.infinity,
              fit: BoxFit.fitWidth,
              // No art (yet) for this world → gradient + particles carry it.
              errorBuilder: (context, error, stack) => const SizedBox.shrink(),
            ),
          ),
          AnimatedBuilder(
            animation: _drift,
            builder: (context, _) => CustomPaint(
              painter: _ParticlePainter(
                t: _drift.value,
                emoji: theme.particles,
                seed: widget.unitId,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _Particle {
  const _Particle(this.xPhase, this.y, this.speed, this.size, this.sway,
      this.phase, this.emojiIndex);
  final double xPhase; // starting x as a fraction of the loop
  final double y; // resting height as a fraction of the screen
  final double speed; // horizontal loops per drift cycle
  final double size;
  final double sway; // vertical bob amplitude (px)
  final double phase;
  final int emojiIndex;
}

class _ParticlePainter extends CustomPainter {
  _ParticlePainter({required this.t, required this.emoji, required this.seed})
      : _particles = _fieldFor(seed);

  final double t;
  final List<String> emoji;
  final int seed;
  final List<_Particle> _particles;

  // One deterministic particle field per world (stable across repaints).
  static final Map<int, List<_Particle>> _cache = {};

  static List<_Particle> _fieldFor(int seed) => _cache.putIfAbsent(seed, () {
        final r = Random(seed * 97 + 5);
        return [
          for (var i = 0; i < 11; i++)
            _Particle(
              r.nextDouble(),
              0.06 + r.nextDouble() * 0.48, // keep the air, avoid the horizon
              1 + r.nextInt(3).toDouble(),
              16 + r.nextDouble() * 12,
              6 + r.nextDouble() * 10,
              r.nextDouble() * pi * 2,
              i,
            ),
        ];
      });

  @override
  void paint(Canvas canvas, Size size) {
    for (final p in _particles) {
      // Drift across (wrapping past both edges), bobbing gently.
      final x = (((p.xPhase + t * p.speed) % 1.1) - 0.05) * size.width;
      final y = p.y * size.height + sin(t * pi * 2 * 3 + p.phase) * p.sway;
      final tp = TextPainter(
        text: TextSpan(
            text: emoji[p.emojiIndex % emoji.length],
            style: TextStyle(fontSize: p.size)),
        textDirection: TextDirection.ltr,
      )..layout();
      tp.paint(canvas, Offset(x, y));
    }
  }

  @override
  bool shouldRepaint(_ParticlePainter old) =>
      old.t != t || old.seed != seed || old.emoji != emoji;
}
